# Generated by Django 3.0.3 on 2020-04-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
