# Generated by Django 3.0.5 on 2020-05-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0003_buddyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Request'), (1, 'Offer')], default=0),
            preserve_default=False,
        ),
    ]
