# Generated by Django 3.0.5 on 2020-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0004_auto_20200503_1615'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('skill', 'profile'), name='unique_skill'),
        ),
    ]
