# Generated by Django 3.0.5 on 2020-05-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0006_auto_20200521_1611'),
        ('buddy_mentorship', '0004_buddyrequest_request_type'),
    ]

    operations = [
    ]
