# Generated by Django 3.1a1 on 2020-05-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0007_merge_20200523_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
