# Generated by Django 3.1a1 on 2020-06-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("buddy_mentorship", "0010_auto_20200614_1759"),
        ("buddy_mentorship", "0011_auto_20200614_2233"),
    ]

    dependencies = [
        ("buddy_mentorship", "0009_skill_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
