# Generated by Django 3.1a1 on 2020-06-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0010_auto_20200614_1759_squashed_0011_auto_20200614_2233'),
        ('buddy_mentorship', '0010_auto_20200615_0130'),
    ]

    operations = [
    ]
