# Generated by Django 3.1a1 on 2020-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_mentorship', '0011_merge_20200620_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
