# Generated by Django 3.1a1 on 2020-07-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddy_mentorship", "0012_auto_20200704_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="looking_for_mentees",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="looking_for_mentors",
            field=models.BooleanField(default=True),
        ),
    ]
