# Generated by Django 3.0.3 on 2020-04-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200411_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
